title: "Blockchain Commons"
project: "Blockchain Commons"
description: "Creating Open, Interoperable, Secure, and Compassionate Infrastructure"
author: Blockchain Commons
email: info@BlockchainCommons.com
image: https://www.blockchaincommons.com/images/bcc-card.jpg
twitter_username: BlockchainComns
github_username:  BlockchainCommons
show_downloads: false
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
remote_theme: blockchaincommons/so-simple-theme
gfm_quirks: paragraph_end

# Plugins
# ========================================================================================

plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

locale: en-US
baseurl: "/"
url: "https://www.BlockchainCommons.com"
logo: images/Borromean-rings_minimal-overlap(256x256).png
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
image:
  path: images/Borromean-rings_minimal-overlap(256x256).png
  height: 256
  width: 256
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
# disqus:
#   shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: BlockchainComns

# Liquid
liquid:
  error_mode: strict

excerpt_separator: <!--more-->  # you can specify your own separator, of course.

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      is_post: true

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/BlockchainComns
    icon: fab fa-twitter-square
  - title: Github
    url: https://github.com/BlockchainCommons/
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
